{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- /* Ingress sources are configurable. Default to open to avoid breaking clusters. */ -}}
        {{- if eq .Values.networkPolicy.allowIngressFrom "ingressController" }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressController.namespace | quote }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressController.podSelector | nindent 12 }}
        {{- else if eq .Values.networkPolicy.allowIngressFrom "namespaces" }}
        {{- range $ns := .Values.networkPolicy.allowedNamespaces }}
        - namespaceSelector:
            matchNames:
              - {{ $ns | quote }}
        {{- end }}
        {{- else if eq .Values.networkPolicy.allowIngressFrom "cidrs" }}
        {{- range $cidr := .Values.networkPolicy.allowedCidrs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
        {{- end }}
        {{- else }}
        - ipBlock:
            cidr: 0.0.0.0/0
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.port }}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
    {{- range $cidr := .Values.networkPolicy.extraEgressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ $cidr | quote }}
    {{- end }}
{{- end }}
