replicaCount: 2
image:
  repository: ghcr.io/OWNER/filip-herceg-cv
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: yourdomain.tld
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
env:
  CONTACT_PROVIDER_API_KEY: ''
  CONTACT_FROM_ADDRESS: 'portfolio@yourdomain.tld'
  CONTACT_TO_ADDRESS: 'you@yourdomain.tld'
