name: CD
on:
  push:
    branches: [main]
concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
      - uses: azure/setup-helm@v4
      - name: Kube config
        run: |
          kubectl config set-cluster cluster --server="${{ secrets.K8S_SERVER }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials deployer --token="${{ secrets.K8S_TOKEN }}"
          kubectl config set-context ctx --cluster=cluster --user=deployer
          kubectl config use-context ctx
      - name: Create namespace
        run: kubectl get ns portfolio || kubectl create ns portfolio
      - name: Set image tag
        id: img
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - name: Helm upgrade
        run: |
          helm upgrade --install web ./helm \
            --namespace portfolio \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=${{ steps.img.outputs.TAG }} \
            --set ingress.host=${{ secrets.INGRESS_HOST }}
      - name: Wait for rollout
        run: |
          DEPLOY_NAME=$(helm status web --namespace portfolio -o json | jq -r '.manifest' | grep -m1 '^kind: Deployment' -n | xargs -I{} bash -lc "yq e 'select(.kind==\"Deployment\") | .metadata.name' - <<< \"$(helm get manifest web -n portfolio)\"")
          kubectl rollout status deployment/$DEPLOY_NAME -n portfolio --timeout=120s
