name: Helm Lint & Render
on:
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.3
      - name: Helm lint
        run: helm lint ./helm
      - name: Render manifests
        run: |
          helm template cv ./helm --values ./helm/values.yaml > k8s/base/all.yaml
      - name: Validate manifests with kubeconform
        run: |
          docker run --rm -v $PWD:/work -w /work ghcr.io/yannh/kubeconform:latest \
            -strict -ignore-missing-schemas -summary k8s/base/all.yaml
      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: k8s-manifests
          path: k8s/base/all.yaml
          retention-days: 5
